version: '3'
services:
  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_NAME: strapi
      DATABASE_HOST: mariadb
      DATABASE_PORT: 3306
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: user123
    depends_on:
      - mariadb
    links:
      - mariadb:mariadb
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: strapi
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    volumes:
     - ./data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080